// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/remote.proto

package remote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqType int32

const (
	ReqType_GetDevices     ReqType = 1
	ReqType_SetDeviceState ReqType = 2
)

var ReqType_name = map[int32]string{
	1: "GetDevices",
	2: "SetDeviceState",
}

var ReqType_value = map[string]int32{
	"GetDevices":     1,
	"SetDeviceState": 2,
}

func (x ReqType) Enum() *ReqType {
	p := new(ReqType)
	*p = x
	return p
}

func (x ReqType) String() string {
	return proto.EnumName(ReqType_name, int32(x))
}

func (x *ReqType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ReqType_value, data, "ReqType")
	if err != nil {
		return err
	}
	*x = ReqType(value)
	return nil
}

func (ReqType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fcb3afbf69ac5ce5, []int{0}
}

type Device struct {
	IeeeAddr             *uint64  `protobuf:"varint,1,req,name=ieeeAddr" json:"ieeeAddr,omitempty"`
	Model                *string  `protobuf:"bytes,2,req,name=model" json:"model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb3afbf69ac5ce5, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetIeeeAddr() uint64 {
	if m != nil && m.IeeeAddr != nil {
		return *m.IeeeAddr
	}
	return 0
}

func (m *Device) GetModel() string {
	if m != nil && m.Model != nil {
		return *m.Model
	}
	return ""
}

type GetDevicesResp struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDevicesResp) Reset()         { *m = GetDevicesResp{} }
func (m *GetDevicesResp) String() string { return proto.CompactTextString(m) }
func (*GetDevicesResp) ProtoMessage()    {}
func (*GetDevicesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb3afbf69ac5ce5, []int{1}
}

func (m *GetDevicesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDevicesResp.Unmarshal(m, b)
}
func (m *GetDevicesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDevicesResp.Marshal(b, m, deterministic)
}
func (m *GetDevicesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDevicesResp.Merge(m, src)
}
func (m *GetDevicesResp) XXX_Size() int {
	return xxx_messageInfo_GetDevicesResp.Size(m)
}
func (m *GetDevicesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDevicesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDevicesResp proto.InternalMessageInfo

func (m *GetDevicesResp) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type SetDeviceStateReq struct {
	IeeeAddr *uint64 `protobuf:"varint,1,req,name=ieeeAddr" json:"ieeeAddr,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*SetDeviceStateReq_Onoff
	//	*SetDeviceStateReq_Level
	Data                 isSetDeviceStateReq_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SetDeviceStateReq) Reset()         { *m = SetDeviceStateReq{} }
func (m *SetDeviceStateReq) String() string { return proto.CompactTextString(m) }
func (*SetDeviceStateReq) ProtoMessage()    {}
func (*SetDeviceStateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb3afbf69ac5ce5, []int{2}
}

func (m *SetDeviceStateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDeviceStateReq.Unmarshal(m, b)
}
func (m *SetDeviceStateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDeviceStateReq.Marshal(b, m, deterministic)
}
func (m *SetDeviceStateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDeviceStateReq.Merge(m, src)
}
func (m *SetDeviceStateReq) XXX_Size() int {
	return xxx_messageInfo_SetDeviceStateReq.Size(m)
}
func (m *SetDeviceStateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDeviceStateReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetDeviceStateReq proto.InternalMessageInfo

func (m *SetDeviceStateReq) GetIeeeAddr() uint64 {
	if m != nil && m.IeeeAddr != nil {
		return *m.IeeeAddr
	}
	return 0
}

type isSetDeviceStateReq_Data interface {
	isSetDeviceStateReq_Data()
}

type SetDeviceStateReq_Onoff struct {
	Onoff bool `protobuf:"varint,2,opt,name=onoff,oneof"`
}

type SetDeviceStateReq_Level struct {
	Level float32 `protobuf:"fixed32,3,opt,name=level,oneof"`
}

func (*SetDeviceStateReq_Onoff) isSetDeviceStateReq_Data() {}

func (*SetDeviceStateReq_Level) isSetDeviceStateReq_Data() {}

func (m *SetDeviceStateReq) GetData() isSetDeviceStateReq_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SetDeviceStateReq) GetOnoff() bool {
	if x, ok := m.GetData().(*SetDeviceStateReq_Onoff); ok {
		return x.Onoff
	}
	return false
}

func (m *SetDeviceStateReq) GetLevel() float32 {
	if x, ok := m.GetData().(*SetDeviceStateReq_Level); ok {
		return x.Level
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SetDeviceStateReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SetDeviceStateReq_Onoff)(nil),
		(*SetDeviceStateReq_Level)(nil),
	}
}

type StatusResp struct {
	Status               *int32   `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResp) Reset()         { *m = StatusResp{} }
func (m *StatusResp) String() string { return proto.CompactTextString(m) }
func (*StatusResp) ProtoMessage()    {}
func (*StatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb3afbf69ac5ce5, []int{3}
}

func (m *StatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResp.Unmarshal(m, b)
}
func (m *StatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResp.Marshal(b, m, deterministic)
}
func (m *StatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResp.Merge(m, src)
}
func (m *StatusResp) XXX_Size() int {
	return xxx_messageInfo_StatusResp.Size(m)
}
func (m *StatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResp proto.InternalMessageInfo

func (m *StatusResp) GetStatus() int32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

type Req struct {
	Type                 *ReqType           `protobuf:"varint,1,req,name=type,enum=remote.ReqType" json:"type,omitempty"`
	SetDeviceState       *SetDeviceStateReq `protobuf:"bytes,2,opt,name=setDeviceState" json:"setDeviceState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb3afbf69ac5ce5, []int{4}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetType() ReqType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ReqType_GetDevices
}

func (m *Req) GetSetDeviceState() *SetDeviceStateReq {
	if m != nil {
		return m.SetDeviceState
	}
	return nil
}

func init() {
	proto.RegisterEnum("remote.ReqType", ReqType_name, ReqType_value)
	proto.RegisterType((*Device)(nil), "remote.Device")
	proto.RegisterType((*GetDevicesResp)(nil), "remote.GetDevicesResp")
	proto.RegisterType((*SetDeviceStateReq)(nil), "remote.SetDeviceStateReq")
	proto.RegisterType((*StatusResp)(nil), "remote.StatusResp")
	proto.RegisterType((*Req)(nil), "remote.Req")
}

func init() { proto.RegisterFile("api/remote.proto", fileDescriptor_fcb3afbf69ac5ce5) }

var fileDescriptor_fcb3afbf69ac5ce5 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0x6c, 0xfe, 0xb4, 0xef, 0x14, 0xd6, 0xb8, 0x48, 0x89, 0x9e, 0x42, 0xf4, 0xb0,
	0x08, 0x56, 0xc8, 0xb1, 0xb7, 0x8a, 0xa0, 0xe7, 0xa9, 0x5f, 0x20, 0xb8, 0x53, 0x09, 0x24, 0xee,
	0x36, 0x59, 0x0b, 0xfd, 0xf6, 0x92, 0xdd, 0x44, 0xa9, 0x82, 0xc7, 0xdf, 0xcc, 0x3c, 0x4f, 0x7e,
	0x59, 0x48, 0x2b, 0x53, 0xdf, 0x77, 0xd4, 0x6a, 0x4b, 0x2b, 0xd3, 0x69, 0xab, 0x45, 0xe2, 0xa9,
	0x58, 0x43, 0xf2, 0x48, 0x87, 0xfa, 0x95, 0xc4, 0x15, 0xcc, 0x6b, 0x22, 0xda, 0x28, 0xd5, 0x65,
	0x41, 0xce, 0x64, 0x84, 0x5f, 0x2c, 0x2e, 0x20, 0x6e, 0xb5, 0xa2, 0x26, 0x63, 0x39, 0x93, 0xff,
	0xd1, 0x43, 0xb1, 0x06, 0xfe, 0x44, 0xd6, 0xc7, 0x7b, 0xa4, 0xde, 0x08, 0x09, 0x33, 0xe5, 0x31,
	0x0b, 0xf2, 0x50, 0x2e, 0x4a, 0xbe, 0x1a, 0xbf, 0xea, 0xaf, 0x70, 0x5a, 0x17, 0x6f, 0x70, 0xbe,
	0x9d, 0xb2, 0x5b, 0x5b, 0x59, 0x42, 0xda, 0xff, 0xa9, 0xb0, 0x84, 0x58, 0xbf, 0xeb, 0xdd, 0x2e,
	0x63, 0x79, 0x20, 0xe7, 0xcf, 0xff, 0xd0, 0xe3, 0x30, 0x6f, 0xe8, 0x40, 0x4d, 0x16, 0xe6, 0x81,
	0x64, 0xc3, 0xdc, 0xe1, 0x43, 0x02, 0x91, 0xaa, 0x6c, 0x55, 0xdc, 0x00, 0x0c, 0xfd, 0x1f, 0x5e,
	0x70, 0x09, 0x49, 0xef, 0xc8, 0xf5, 0xc7, 0x38, 0x52, 0xd1, 0x42, 0x38, 0x08, 0x5c, 0x43, 0x64,
	0x8f, 0x86, 0xdc, 0x92, 0x97, 0x67, 0x93, 0x3c, 0xd2, 0xfe, 0xe5, 0x68, 0x08, 0xdd, 0x52, 0x6c,
	0x80, 0xf7, 0x27, 0xea, 0x4e, 0x69, 0x51, 0x5e, 0x4e, 0xe7, 0xbf, 0x7e, 0x0c, 0x7f, 0x04, 0x6e,
	0xef, 0x60, 0x36, 0x76, 0x0a, 0x0e, 0xf0, 0xfd, 0x88, 0x69, 0x20, 0x04, 0xf0, 0xd3, 0x7c, 0xca,
	0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x06, 0x6a, 0x5f, 0x8a, 0xbf, 0x01, 0x00, 0x00,
}
